### PR TITLE
New

### PR DESCRIPTION
**Pull request by ausgates**

### CODE REVIEW

**Comment by ausgates** [comment]
Made this bitch responsive

**Comment by probablyjosh** [comment]
why did you change so many little things in basically every file

**Comment by probablyjosh** [comment]
fuck it

**Comment by ausgates** [comment]
I did not?

On Wed, May 13, 2015 at 5:53 PM, Josh Trommel <notifications@github.com>
wrote:

> Merged #3 <https://github.com/probablyjosh/site/pull/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/probablyjosh/site/pull/3#event-304341840>.
>



-- 
Austin Gates
austingates16@gmail.com

**Comment by probablyjosh** [comment]
screen shot 2015-05-13 at 4 43 27 pm

**Comment by ausgates** [comment]
Oh you know why, because I put the pull request in for the master branch
not the new branch.

On Wed, May 13, 2015 at 7:43 PM, Josh Trommel <notifications@github.com>
wrote:

> [image: screen shot 2015-05-13 at 4 43 27 pm]
> <https://cloud.githubusercontent.com/assets/4617414/7623435/309832fe-f98f-11e4-958e-3e799223d0f2.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/probablyjosh/site/pull/3#issuecomment-101850437>.
>



-- 
Austin Gates
austingates16@gmail.com

**Comment by probablyjosh** [comment]
ah shit ok

**Pull request merged**
